export const CREATE_MONSTER = "CREATE_MONSTER";
export const UPDATE_STAT = "UPDATE_STAT";

export const PUSH_POWER = "PUSH_POWER";
export const DELETE_POWER = "DELETE_POWER";


export const ASYNC_START = "ASYNC_START";
export const ASYNC_FAIL = "ASYNC_FAIL";
export const SAVE_SUCCESS = "SAVE_SUCCESS";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const FETCH_MONSTERS_SUCCESS = "FETCH_MONSTERS_SUCCESS";
export const FETCH_MONSTERS = "FETCH_MONSTERS";
export const LOAD_MONSTER = "LOAD_MONSTER";
export const LOAD_MONSTER_ID = "LOAD_MONSTER_ID";
export const DELETE_SUCCESS = "DELETE_SUCCESS";

export const FETCH_TEMPLATES_SUCCESS = "FETCH_TEMPLATES_SUCCESS";
export const SAVE_TEMPLATE_SUCCESS = "SAVE_TEMPLATE_SUCCESS";